### ISSUE TITLE
发现一个严重问题，内存泄漏。

### ISSUE THREAD

**Issue by marscl** [wenwenwen888/SearchDialog#10]
打开搜索框 后关闭会发生泄漏。

**Comment by wenwenwen888** [comment]
@marscl 有日志吗

**Comment by marscl** [comment]
* com.wyt.searchbox.SearchFragment has leaked:
* ActivityThread$ApplicationThread.this$0
* ↳ ActivityThread.mActivities
* ↳ ArrayMap.mArray
* ↳ array Object[].[1]
* ↳ ActivityThread$ActivityClientRecord.activity
* ↳ Main3Activity.!(searchFragment)!
* ↳ SearchFragment

* Reference Key: e03d43b0-d31a-4654-a6e7-6afe78ff4efd
* Device: Meizu Meizu M5 Note meizu_M5 Note
* Android Version: 7.0 API: 24 LeakCanary: 1.6.1 26145bf
* Durations: watch=38288ms, gc=151ms, heap dump=4127ms, analysis=27520ms

* Details:
* Instance of android.app.ActivityThread$ApplicationThread
|   static DB_INFO_FORMAT = "  %8s %8s %14s %14s  %s"
|   static $classOverhead = byte[644]@1864611857 (0x6f23b811)
|   mLastProcessState = 2
|   this$0 = android.app.ActivityThread@320164096 (0x13155100)
|   mDescriptor = "android.app.IApplicationThread"
|   mObject = -441683344
|   mOwner = android.app.ActivityThread$ApplicationThread@320040672 (0x13136ee0)
|   shadow$_klass_ = android.app.ActivityThread$ApplicationThread
|   shadow$_monitor_ = 0
* Instance of android.app.ActivityThread
|   static THUMBNAIL_FORMAT = android.graphics.Bitmap$Config@1863496432 (0x6f12b2f0)
|   static AT_CLOSE = 0
|   static HEAP_FULL_COLUMN = "%13s %8s %8s %8s %8s %8s %8s %8s %8s %8s %8s"
|   static SUPPRESS_ACTION_ALLOWED = 0
|   static HEAP_COLUMN = "%13s %8s %8s %8s %8s %8s %8s %8s"
|   static DEBUG_BACKUP = false
|   static sCurrentBroadcastIntent = java.lang.ThreadLocal@1946925808 (0x740bbaf0)
|   static DEBUG_RESULTS = false
|   static MIN_TIME_BETWEEN_GCS = 5000
|   static TWO_COUNT_COLUMNS = "%21s %8d %21s %8d"
|   static SERVICE_DONE_EXECUTING_START = 1
|   static LOG_AM_ON_PAUSE_CALLED = 30021
|   static mIsEngBuild = false
|   static ACTIVITY_THREAD_CHECKIN_VERSION = 4
|   static DEBUG_ORDER = false
|   static LOG_AM_ON_RESUME_CALLED = 30022
|   static SUPPRESS_TIME = 5000
|   static DEBUG_CONFIGURATION = false
|   static IS_USER_BUILD = true
|   static IS_USER_DEBUG_BUILD = false
|   static USER_LEAVING = 1
|   static REPORT_TO_ACTIVITY = true
|   static SUPPRESS_ACTION_DELAYED = 1
|   static DEBUG_MEMORY_TRIM = false
|   static localLOGV = false
|   static AT_OPEN = 1
|   static SQLITE_MEM_RELEASED_EVENT_LOG_TAG = 75003
|   static LOG_AM_ON_STOP_CALLED = 30049
|   static sCurrentActivityThread = android.app.ActivityThread@320164096 (0x13155100)
|   static DEBUG_PROVIDER = false
|   static DEBUG_BROADCAST = false
|   static SERVICE_DONE_EXECUTING_STOP = 2
|   static sMainThreadHandler = android.app.ActivityThread$H@320040704 (0x13136f00)
|   static DEBUG_LIFECYCLE = false
|   static $classOverhead = byte[712]@1862835833 (0x6f089e79)
|   static DEBUG_MESSAGES = false
|   static mEnableAppLaunchLog = false
|   static DONT_REPORT = 2
|   static DEBUG_SERVICE = false
|   static sPackageManager = android.content.pm.IPackageManager$Stub$Proxy@320386192 (0x1318b490)
|   static TAG = "ActivityThread"
|   static ONE_COUNT_COLUMN = "%21s %8d"
|   static SERVICE_DONE_EXECUTING_ANON = 0
|   static ONE_COUNT_COLUMN_HEADER = "%21s %8s"
|   mActivities = android.util.ArrayMap@320018640 (0x131318d0)
|   mAllApplications = java.util.ArrayList@320115880 (0x131494a8)
|   mAppThread = android.app.ActivityThread$ApplicationThread@320040672 (0x13136ee0)
|   mAvailThumbnailBitmap = null
|   mBackupAgents = android.util.ArrayMap@320018720 (0x13131920)
|   mBoundApplication = android.app.ActivityThread$AppBindData@320266368 (0x1316e080)
|   mCompatConfiguration = android.content.res.Configuration@319958312 (0x13122d28)
|   mConfiguration = android.content.res.Configuration@319958208 (0x13122cc0)
|   mCoreSettings = android.os.Bundle@320229872 (0x131651f0)
|   mCurDefaultDisplayDpi = 480
|   mDensityCompatMode = false
|   mGcIdler = android.app.ActivityThread$GcIdler@320100768 (0x131459a0)
|   mGcIdlerScheduled = false
|   mH = android.app.ActivityThread$H@320040704 (0x13136f00)
|   mInitialApplication = com.marsvideo.util.MyApplication@320418488 (0x131932b8)
|   mInstrumentation = android.app.Instrumentation@320422096 (0x131940d0)
|   mInstrumentationAppDir = null
|   mInstrumentationLibDir = null
|   mInstrumentationPackageName = null
|   mInstrumentationSplitAppDirs = null
|   mInstrumentedAppDir = null
|   mInstrumentedLibDir = null
|   mInstrumentedSplitAppDirs = null
|   mJitEnabled = true
|   mLastAssistStructures = java.util.ArrayList@320115856 (0x13149490)
|   mLastSessionId = 0
|   mLifecycleSeq = 29
|   mLocalProviders = android.util.ArrayMap@320018920 (0x131319e8)
|   mLocalProvidersByName = android.util.ArrayMap@320018960 (0x13131a10)
|   mLooper = android.os.Looper@320040640 (0x13136ec0)
|   mMainThreadConfig = android.content.res.Configuration@319958000 (0x13122bf0)
|   mNewActivities = null
|   mNumVisibleActivities = 1
|   mOnPauseListeners = android.util.ArrayMap@320019000 (0x13131a38)
|   mPackages = android.util.ArrayMap@320018760 (0x13131948)
|   mPendingConfiguration = null
|   mProfiler = android.app.ActivityThread$Profiler@320116120 (0x13149598)
|   mProviderMap = android.util.ArrayMap@320018840 (0x13131998)
|   mProviderRefCountMap = android.util.ArrayMap@320018880 (0x131319c0)
|   mRelaunchingActivities = java.util.ArrayList@320115904 (0x131494c0)
|   mResourcePackages = android.util.ArrayMap@320018800 (0x13131970)
|   mResourcesManager = android.app.ResourcesManager@320040736 (0x13136f20)
|   mServices = android.util.ArrayMap@320018680 (0x131318f8)
|   mSomeActivitiesChanged = true
|   mSystemContext = null
|   mSystemThread = false
|   mThumbnailCanvas = null
|   mThumbnailHeight = -1
|   mThumbnailWidth = -1
|   shadow$_klass_ = android.app.ActivityThread
|   shadow$_monitor_ = 0
* Instance of android.util.ArrayMap
|   static CACHE_SIZE = 10
|   static EMPTY_IMMUTABLE_INTS = int[0]@1946921216 (0x740ba900)
|   static mTwiceBaseCache = null
|   static DEBUG = false
|   static mBaseCache = null
|   static EMPTY = android.util.ArrayMap@1946921176 (0x740ba8d8)
|   static $classOverhead = byte[506]@1862798697 (0x6f080d69)
|   static static_id = 10967
|   static IS_PRD_BUILD = true
|   static BASE_SIZE = 4
|   static mBaseCacheSize = 0
|   static mTwiceBaseCacheSize = 0
|   static TAG = "ArrayMap"
|   id = 10041
|   mArray = java.lang.Object[8]@318025984 (0x12f4b100)
|   mCollections = null
|   mHashes = int[4]@317877120 (0x12f26b80)
|   mIdentityHashCode = false
|   mMultiStatus = 0
|   mSize = 1
|   shadow$_klass_ = android.util.ArrayMap
|   shadow$_monitor_ = 0
* Array of java.lang.Object[]
|   [0] = android.os.BinderProxy@325296224 (0x1363a060)
|   [1] = android.app.ActivityThread$ActivityClientRecord@325316992 (0x1363f180)
|   [2] = null
|   [3] = null
|   [4] = null
|   [5] = null
|   [6] = null
|   [7] = null
* Instance of android.app.ActivityThread$ActivityClientRecord
|   static $classOverhead = byte[316]@1865083497 (0x6f2aea69)
|   activity = com.marsvideo.Main3Activity@325468512 (0x13664160)
|   activityInfo = android.content.pm.ActivityInfo@325033552 (0x135f9e50)
|   compatInfo = android.content.res.CompatibilityInfo@315334960 (0x12cba130)
|   createdConfig = null
|   embeddedID = null
|   hideForNow = false
|   ident = 119072175
|   intent = android.content.Intent@315322560 (0x12cb70c0)
|   isForward = false
|   lastNonConfigurationInstances = null
|   lastProcessedSeq = 28
|   mPendingRemoveWindow = null
|   mPendingRemoveWindowManager = null
|   mPreserveWindow = false
|   newConfig = null
|   nextIdle = null
|   onlyLocalRequest = false
|   overrideConfig = android.content.res.Configuration@325325048 (0x136410f8)
|   packageInfo = android.app.LoadedApk@319998656 (0x1312cac0)
|   parent = null
|   paused = false
|   pendingConfigChanges = 0
|   pendingIntents = null
|   pendingResults = null
|   persistentState = null
|   profilerInfo = null
|   relaunchSeq = 0
|   startsNotResumed = false
|   state = null
|   stopped = false
|   tmpConfig = android.content.res.Configuration@325325152 (0x13641160)
|   token = android.os.BinderProxy@325296224 (0x1363a060)
|   voiceInteractor = null
|   window = com.android.internal.policy.PhoneWindow@319506640 (0x130b48d0)
|   shadow$_klass_ = android.app.ActivityThread$ActivityClientRecord
|   shadow$_monitor_ = 0
* Instance of com.marsvideo.Main3Activity
|   static $change = null
|   static serialVersionUID = -1134440581035675198
|   static $classOverhead = byte[2296]@320503809 (0x131a8001)
|   firstTime = 0
|   searchFragment = com.wyt.searchbox.SearchFragment@325633632 (0x1368c660)
|   toolbar = android.support.v7.widget.Toolbar@325508096 (0x1366dc00)
|   mDelegate = android.support.v7.app.AppCompatDelegateImplN@325399888 (0x13653550)
|   mResources = null
|   mThemeId = 2131427510
|   mCreated = true
|   mFragments = android.support.v4.app.FragmentController@325245344 (0x1362d9a0)
|   mHandler = android.support.v4.app.FragmentActivity$1@325241440 (0x1362ca60)
|   mNextCandidateRequestIndex = 0
|   mPendingFragmentActivityResults = android.support.v4.util.SparseArrayCompat@325250448 (0x1362ed90)
|   mReallyStopped = false
|   mRequestedPermissionsFromFragment = false
|   mResumed = true
|   mRetaining = false
|   mStopped = false
|   mStartedActivityFromFragment = false
|   mStartedIntentSenderFromFragment = false
|   mExtraDataMap = android.support.v4.util.SimpleArrayMap@325249368 (0x1362e958)
|   mLifecycleRegistry = android.arch.lifecycle.LifecycleRegistry@325241376 (0x1362ca20)
|   mActionBar = null
|   mActionBarToTop = false
|   mActionModeTypeStarting = 0
|   mActivityInfo = android.content.pm.ActivityInfo@325033552 (0x135f9e50)
|   mActivityTransitionState = android.app.ActivityTransitionState@325192328 (0x13620a88)
|   mApplication = com.video.util.MyApplication@320418488 (0x131932b8)
|   mCalled = true
|   mChangeCanvasToTranslucent = false
|   mChangingConfigurations = false
|   mComponent = android.content.ComponentName@325304400 (0x1363c050)
|   mConfigChangeFlags = 0
|   mCurrentConfig = android.content.res.Configuration@325284400 (0x13637230)
|   mDecor = com.android.internal.policy.DecorView@325501952 (0x1366c400)
|   mDefaultKeyMode = 0
|   mDefaultKeySsb = null
|   mDestroyed = false
|   mDoReportFullyDrawn = false
|   mEatKeyUpEvent = false
|   mEmbeddedID = null
|   mEnableDefaultActionBarUp = false
|   mEnterTransitionListener = android.app.SharedElementCallback$1@1863490256 (0x6f129ad0)
|   mExitTransitionListener = android.app.SharedElementCallback$1@1863490256 (0x6f129ad0)
|   mFinished = false
|   mFragments = android.app.FragmentController@325245280 (0x1362d960)
|   mHandler = android.os.Handler@325241312 (0x1362c9e0)
|   mHasCurrentPermissionsRequest = false
|   mIdent = 119072175
|   mInstanceTracker = android.os.StrictMode$InstanceTracker@325245296 (0x1362d970)
|   mInstrumentation = android.app.Instrumentation@320422096 (0x131940d0)
|   mIntent = android.content.Intent@315322560 (0x12cb70c0)
|   mLastNonConfigurationInstances = null
|   mMainThread = android.app.ActivityThread@320164096 (0x13155100)
|   mManagedCursors = java.util.ArrayList@325249320 (0x1362e928)
|   mManagedDialogs = null
|   mMenuInflater = null
|   mParent = null
|   mResultCode = 0
|   mResultData = null
|   mResumed = true
|   mSearchEvent = null
|   mSearchManager = null
|   mStartedActivity = false
|   mStopped = false
|   mTaskDescription = android.app.ActivityManager$TaskDescription@325241344 (0x1362ca00)
|   mTemporaryPause = false
|   mTitleColor = 0
|   mTitleReady = true
|   mToken = android.os.BinderProxy@325296224 (0x1363a060)
|   mTranslucentCallback = null
|   mUiThread = java.lang.Thread@1946610048 (0x7406e980)
|   mVisibleBehind = false
|   mVisibleFromClient = true
|   mVisibleFromServer = true
|   mVoiceInteractor = null
|   mWindow = com.android.internal.policy.PhoneWindow@319506640 (0x130b48d0)
|   mWindowAdded = true
|   mWindowManager = android.view.WindowManagerImpl@325249776 (0x1362eaf0)
|   scrollCallback = null
|   mInflater = com.android.internal.policy.PhoneLayoutInflater@325453328 (0x13660610)
|   mOverrideConfiguration = null
|   mResources = android.content.res.Resources@325232928 (0x1362a920)
|   mTheme = android.content.res.Resources$Theme@325245552 (0x1362da70)
|   mThemeResource = 2131427510
|   mBase = android.app.ContextImpl@321437360 (0x1328beb0)
|   mColorThemeCacheMap = java.util.HashMap@325232688 (0x1362a830)
|   shadow$_klass_ = com.marsvideo.Main3Activity
|   shadow$_monitor_ = -2050207438
* Instance of com.wyt.searchbox.SearchFragment
|   static TAG = "SearchFragment"
|   static $classOverhead = byte[1012]@325894145 (0x136cc001)
|   allHistorys = java.util.ArrayList@318431632 (0x12fae190)
|   etSearchKeyword = android.support.v7.widget.AppCompatEditText@315620352 (0x12cffc00)
|   historys = java.util.ArrayList@326088088 (0x136fb598)
|   iOnSearchClickListener = com.marsvideo.Main3Activity$1@326083840 (0x136fa500)
|   ivSearchBack = android.support.v7.widget.AppCompatImageView@315294720 (0x12cb0400)
|   ivSearchSearch = android.support.v7.widget.AppCompatImageView@316488704 (0x12dd3c00)
|   mCircularRevealAnim = com.wyt.searchbox.custom.CircularRevealAnim@316172256 (0x12d867e0)
|   rvSearchHistory = android.support.v7.widget.RecyclerView@317399040 (0x12eb2000)
|   searchHistoryAdapter = com.wyt.searchbox.adapter.SearchHistoryAdapter@317767168 (0x12f0be00)
|   searchHistoryDB = com.wyt.searchbox.db.SearchHistoryDB@316412400 (0x12dc11f0)
|   searchUnderline = android.view.View@314667856 (0x12c17350)
|   tvSearchClean = android.support.v7.widget.AppCompatTextView@317512704 (0x12ecdc00)
|   view = android.widget.LinearLayout@315269120 (0x12caa000)
|   viewSearchOutside = android.view.View@314670176 (0x12c17c60)
|   mBackStackId = -1
|   mCancelable = true
|   mDialog = null
|   mDismissed = true
|   mShownByMe = false
|   mShowsDialog = true
|   mStyle = 2
|   mTheme = 2131427584
|   mViewDestroyed = true
|   mAdded = false
|   mAnimationInfo = null
|   mArguments = android.os.Bundle@326087992 (0x136fb538)
|   mBackStackNesting = 0
|   mCalled = true
|   mCheckedForLoaderManager = false
|   mChildFragmentManager = null
|   mChildNonConfig = null
|   mContainer = null
|   mContainerId = 0
|   mDeferStart = false
|   mDetached = false
|   mFragmentId = 0
|   mFragmentManager = null
|   mFromLayout = false
|   mHasMenu = false
|   mHidden = false
|   mHiddenChanged = false
|   mHost = null
|   mInLayout = false
|   mIndex = -1
|   mInnerView = null
|   mIsCreated = false
|   mIsNewlyAdded = false
|   mLayoutInflater = null
|   mLifecycleRegistry = android.arch.lifecycle.LifecycleRegistry@326064704 (0x136f5a40)
|   mLoaderManager = null
|   mLoadersStarted = false
|   mMenuVisible = true
|   mParentFragment = null
|   mPerformedCreateView = false
|   mPostponedAlpha = 0.0
|   mRemoving = false
|   mRestored = false
|   mRetainInstance = false
|   mRetaining = false
|   mSavedFragmentState = null
|   mSavedViewState = android.util.SparseArray@315335728 (0x12cba430)
|   mState = 0
|   mTag = null
|   mTarget = null
|   mTargetIndex = -1
|   mTargetRequestCode = 0
|   mUserVisibleHint = true
|   mView = null
|   mWho = null
|   shadow$_klass_ = com.wyt.searchbox.SearchFragment
|   shadow$_monitor_ = 0
* Excluded Refs:
| Field: android.os.Message.obj
| Field: android.os.Message.next
| Field: android.os.Message.target
| Field: android.view.inputmethod.InputMethodManager.mNextServedView
| Field: android.view.inputmethod.InputMethodManager.mServedView
| Field: android.view.inputmethod.InputMethodManager.mServedInputConnection
| Field: android.view.inputmethod.InputMethodManager.mCurRootView
| Field: android.view.textservice.SpellCheckerSession$1.this$0
| Field: android.accounts.AccountManager$AmsTask$Response.this$1
| Field: com.android.internal.policy.BackdropFrameRenderer.mDecorView
| Field: android.view.Choreographer$FrameDisplayEventReceiver.mMessageQueue (always)
| Thread:FinalizerWatchdogDaemon (always)
| Thread:main (always)
| Thread:LeakCanary-Heap-Dump (always)
| Class:java.lang.ref.WeakReference (always)
| Class:java.lang.ref.SoftReference (always)
| Class:java.lang.ref.PhantomReference (always)
| Class:java.lang.ref.Finalizer (always)
| Class:java.lang.ref.FinalizerReference (always)

**Comment by wenwenwen888** [comment]
谢谢，有时间我看看
