### ISSUE TITLE
空指针异常：searchFragment.showFragment(getSupportFragmentManager(), SearchFragment.TAG);

### ISSUE THREAD

**Issue by zhubingran** [wenwenwen888/SearchDialog#15]
searchFragment.showFragment(getSupportFragmentManager(), SearchFragment.TAG);
请问这句话报错空指针怎么解决

**Comment by wenwenwen888** [comment]
@zhubingran 有具体日志吗

**Comment by zhubingran** [comment]
有的 稍等一下

**Comment by wenwenwen888** [comment]
@zhubingran 最好使用代码也贴一下看看

**Comment by zhubingran** [comment]
好的

**Comment by zhubingran** [comment]
这个是日志报错：
 Process: com.zbr.waste_sorting, PID: 15851
    java.lang.NullPointerException: Attempt to invoke virtual method 'void com.wyt.searchbox.SearchFragment.showFragment(androidx.fragment.app.FragmentManager, java.lang.String)' on a null object reference
        at com.zbr.waste_sorting.MainActivity.onMenuItemClick(MainActivity.java:107)......


代码就根据你的demo复制过来的
在onCreate()中添加了：
Toolbar toolbar = findViewById(R.id.toolbar);
        setSupportActionBar(toolbar);
        toolbar.setOnMenuItemClickListener(this);

还定义了    
@Override
    public boolean onCreateOptionsMenu(Menu menu) {
        //加载菜单文件
        getMenuInflater().inflate(R.menu.menu_main, menu);
        return true;
    }

    @Override
    public boolean onMenuItemClick(MenuItem item) {
        switch (item.getItemId()) {
            case R.id.action_search://点击搜索
                searchFragment.showFragment(getSupportFragmentManager(), SearchFragment.TAG);
                break;
        }
        return true;
    }

    public void OnSearchClick(String keyword) {
        Toast.makeText(this,keyword,Toast.LENGTH_LONG).show();
    }

**Comment by wenwenwen888** [comment]
实例化了吗
```
 SearchFragment searchFragment = SearchFragment.newInstance();
```

**Comment by zhubingran** [comment]
在onCreate()中实例化了

**Comment by wenwenwen888** [comment]
加我QQ：825570853 帮你看看
