### ISSUE TITLE
使用过之后的小建议

### ISSUE THREAD

**Issue by 99882847** [wenwenwen888/SearchDialog#3]
整体的效果很棒。但是还是有几个小问题：
1.搜索记录应该过滤掉重复的数据，比如我一直重复搜索相同的内容，记录里会一直存相同的，正常应该只显示一个。
2.能开放一下最多保存几条数据的方法就好了，因为现在有很多项目会限制显示记录的条数。

**Comment by wenwenwen888** [comment]
@99882847 感谢建议 , 有时间就改
