### ISSUE TITLE
重复开启关闭，界面会有残余动画。

### ISSUE THREAD

**Issue by wrz123456** [wenwenwen888/SearchDialog#6]
关闭后再调用
searchFragment.show(getSupportFragmentManager(),SearchFragment.TAG);
..多次后会有残余动画，上一帧显示..然后再消失

**Comment by wenwenwen888** [comment]
我多台手机测试都没有这种问题
你用模拟器或者其他手机测试一下看看

**Comment by wrz123456** [comment]
调试完毕了，使用真机测试，没有这个bug了0.0应该是模拟器cpu模式问题

**Comment by wenwenwen888** [comment]
好的
