### ISSUE TITLE
大佬

### ISSUE THREAD

**Issue by JamieYee** [wenwenwen888/SearchDialog#8]
![image](https://user-images.githubusercontent.com/15099278/34925252-297663ae-f9e3-11e7-878e-f75baa229c50.png)
你可能要更新一下

**Comment by leila-huang** [comment]
我把这个换了之后就饿可以用了。。
`compile 'com.android.support:support-v4:27.0.2'
    compile 'com.android.support:appcompat-v7:27.0.2'
    compile 'com.android.support:recyclerview-v7:27.0.2'
    compile 'com.android.support:design:27.0.2'`
